library(ggplot2)
library(ggpmisc)
datad = read.csv("BSA.csv")
p = ggplot(datad, aes(x = Sample, y = A)) + geom_errorbar(aes(ymin = A - se, ymax = A + se), width = 0.005) + geom_point()
p = p + geom_smooth(method = "lm", se=FALSE, color="black")
p = p + xlab("Concentration of protein (mg/ml)") + ylab("Absorbance") + ggtitle("Bradford Assay")
p = p + stat_poly_eq(use_label(c("eq", "R2"))) + theme_bw()
print(p)
ggsave("Bradford.pdf", width = 3840, height = 2160, units = "px")
